apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/template-mlops-accidents-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
          image: api
          imagePullPolicy: Never  # <- Теперь это внутри контейнера
          name: api
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always