apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: mlflow
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlflow
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/template-mlops-accidents-default: "true"
        io.kompose.service: mlflow
    spec:
      containers:
        - name: mlflow
          image: mlflow
          imagePullPolicy: Never
          command: ["mlflow"]
          args: ["server", "--host", "0.0.0.0", "--port", "5000"]
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /mlruns
              name: mlflow-claim0
      restartPolicy: Always
      volumes:
        - name: mlflow-claim0
          persistentVolumeClaim:
            claimName: mlflow-claim0